### ISSUE TITLE
HTML link testing not actually testing anything

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/ribose-public#4]
For example, see: https://travis-ci.org/riboseinc/ribose-public/builds/483716121#L507

It says,

```
Running ["LinkCheck", "ImageCheck", "ScriptCheck"] on ["./output"] on *.html... 
Checking 0 external links...
Ran on 0 files!
```

**Comment by ronaldtse** [comment]
We need to configure the Rakefile task to actually select the _site directory for testing. In any case, we need to make testing work before it gets enabled (otherwise you’ll see plenty of failures).
